//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SQLQueries {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SQLQueries() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("DAL.SQLQueries", typeof(SQLQueries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Users_SelectAll {
            get {
                return ResourceManager.GetString("Users_SelectAll", resourceCulture);
            }
        }
        
        internal static string Users_SelectById {
            get {
                return ResourceManager.GetString("Users_SelectById", resourceCulture);
            }
        }
        
        internal static string Users_SelectByEmail {
            get {
                return ResourceManager.GetString("Users_SelectByEmail", resourceCulture);
            }
        }
        
        internal static string Users_EmailExists {
            get {
                return ResourceManager.GetString("Users_EmailExists", resourceCulture);
            }
        }
        
        internal static string Users_Insert {
            get {
                return ResourceManager.GetString("Users_Insert", resourceCulture);
            }
        }
        
        internal static string Users_Update {
            get {
                return ResourceManager.GetString("Users_Update", resourceCulture);
            }
        }
        
        internal static string Users_Delete {
            get {
                return ResourceManager.GetString("Users_Delete", resourceCulture);
            }
        }
        
        internal static string Users_UpdateLastLogin {
            get {
                return ResourceManager.GetString("Users_UpdateLastLogin", resourceCulture);
            }
        }
        
        internal static string Hotels_SelectAll {
            get {
                return ResourceManager.GetString("Hotels_SelectAll", resourceCulture);
            }
        }
        
        internal static string Hotels_SelectById {
            get {
                return ResourceManager.GetString("Hotels_SelectById", resourceCulture);
            }
        }
        
        internal static string Hotels_Insert {
            get {
                return ResourceManager.GetString("Hotels_Insert", resourceCulture);
            }
        }
        
        internal static string Hotels_Update {
            get {
                return ResourceManager.GetString("Hotels_Update", resourceCulture);
            }
        }
        
        internal static string Hotels_Delete {
            get {
                return ResourceManager.GetString("Hotels_Delete", resourceCulture);
            }
        }
        
        internal static string Conveniences_SelectAll {
            get {
                return ResourceManager.GetString("Conveniences_SelectAll", resourceCulture);
            }
        }
        
        internal static string Conveniences_SelectById {
            get {
                return ResourceManager.GetString("Conveniences_SelectById", resourceCulture);
            }
        }
        
        internal static string Conveniences_Insert {
            get {
                return ResourceManager.GetString("Conveniences_Insert", resourceCulture);
            }
        }
        
        internal static string Conveniences_Update {
            get {
                return ResourceManager.GetString("Conveniences_Update", resourceCulture);
            }
        }
        
        internal static string Conveniences_Delete {
            get {
                return ResourceManager.GetString("Conveniences_Delete", resourceCulture);
            }
        }
        
        internal static string HotelConveniences_SelectAll {
            get {
                return ResourceManager.GetString("HotelConveniences_SelectAll", resourceCulture);
            }
        }
        
        internal static string HotelConveniences_SelectById {
            get {
                return ResourceManager.GetString("HotelConveniences_SelectById", resourceCulture);
            }
        }
        
        internal static string HotelConveniences_SelectByHotelId {
            get {
                return ResourceManager.GetString("HotelConveniences_SelectByHotelId", resourceCulture);
            }
        }
        
        internal static string HotelConveniences_Insert {
            get {
                return ResourceManager.GetString("HotelConveniences_Insert", resourceCulture);
            }
        }
        
        internal static string HotelConveniences_Delete {
            get {
                return ResourceManager.GetString("HotelConveniences_Delete", resourceCulture);
            }
        }
        
        internal static string HotelConveniences_DeleteByHotelAndConvenience {
            get {
                return ResourceManager.GetString("HotelConveniences_DeleteByHotelAndConvenience", resourceCulture);
            }
        }
        
        internal static string HotelRooms_SelectAll {
            get {
                return ResourceManager.GetString("HotelRooms_SelectAll", resourceCulture);
            }
        }
        
        internal static string HotelRooms_SelectById {
            get {
                return ResourceManager.GetString("HotelRooms_SelectById", resourceCulture);
            }
        }
        
        internal static string HotelRooms_SelectByHotelId {
            get {
                return ResourceManager.GetString("HotelRooms_SelectByHotelId", resourceCulture);
            }
        }
        
        internal static string HotelRooms_Insert {
            get {
                return ResourceManager.GetString("HotelRooms_Insert", resourceCulture);
            }
        }
        
        internal static string HotelRooms_Update {
            get {
                return ResourceManager.GetString("HotelRooms_Update", resourceCulture);
            }
        }
        
        internal static string HotelRooms_Delete {
            get {
                return ResourceManager.GetString("HotelRooms_Delete", resourceCulture);
            }
        }
        
        internal static string HotelRoomConveniences_SelectAll {
            get {
                return ResourceManager.GetString("HotelRoomConveniences_SelectAll", resourceCulture);
            }
        }
        
        internal static string HotelRoomConveniences_SelectById {
            get {
                return ResourceManager.GetString("HotelRoomConveniences_SelectById", resourceCulture);
            }
        }
        
        internal static string HotelRoomConveniences_SelectByRoomId {
            get {
                return ResourceManager.GetString("HotelRoomConveniences_SelectByRoomId", resourceCulture);
            }
        }
        
        internal static string HotelRoomConveniences_Insert {
            get {
                return ResourceManager.GetString("HotelRoomConveniences_Insert", resourceCulture);
            }
        }
        
        internal static string HotelRoomConveniences_Delete {
            get {
                return ResourceManager.GetString("HotelRoomConveniences_Delete", resourceCulture);
            }
        }
        
        internal static string HotelRoomConveniences_DeleteByRoomAndConvenience {
            get {
                return ResourceManager.GetString("HotelRoomConveniences_DeleteByRoomAndConvenience", resourceCulture);
            }
        }
        
        internal static string HotelReservations_SelectById {
            get {
                return ResourceManager.GetString("HotelReservations_SelectById", resourceCulture);
            }
        }
        
        internal static string HotelReservations_SelectByUserId {
            get {
                return ResourceManager.GetString("HotelReservations_SelectByUserId", resourceCulture);
            }
        }
        
        internal static string HotelReservations_SelectByHotelId {
            get {
                return ResourceManager.GetString("HotelReservations_SelectByHotelId", resourceCulture);
            }
        }
        
        internal static string HotelReservations_Insert {
            get {
                return ResourceManager.GetString("HotelReservations_Insert", resourceCulture);
            }
        }
        
        internal static string HotelReservations_Update {
            get {
                return ResourceManager.GetString("HotelReservations_Update", resourceCulture);
            }
        }
        
        internal static string HotelReservations_Delete {
            get {
                return ResourceManager.GetString("HotelReservations_Delete", resourceCulture);
            }
        }
        
        internal static string Currencies_SelectAll {
            get {
                return ResourceManager.GetString("Currencies_SelectAll", resourceCulture);
            }
        }
        
        internal static string Currencies_SelectById {
            get {
                return ResourceManager.GetString("Currencies_SelectById", resourceCulture);
            }
        }
        
        internal static string Currencies_Insert {
            get {
                return ResourceManager.GetString("Currencies_Insert", resourceCulture);
            }
        }
        
        internal static string Currencies_Update {
            get {
                return ResourceManager.GetString("Currencies_Update", resourceCulture);
            }
        }
        
        internal static string Currencies_Delete {
            get {
                return ResourceManager.GetString("Currencies_Delete", resourceCulture);
            }
        }
        
        internal static string HotelPayments_SelectAll {
            get {
                return ResourceManager.GetString("HotelPayments_SelectAll", resourceCulture);
            }
        }
        
        internal static string HotelPayments_SelectById {
            get {
                return ResourceManager.GetString("HotelPayments_SelectById", resourceCulture);
            }
        }
        
        internal static string HotelPayments_SelectByUserId {
            get {
                return ResourceManager.GetString("HotelPayments_SelectByUserId", resourceCulture);
            }
        }
        
        internal static string HotelPayments_Insert {
            get {
                return ResourceManager.GetString("HotelPayments_Insert", resourceCulture);
            }
        }
        
        internal static string HotelPayments_Delete {
            get {
                return ResourceManager.GetString("HotelPayments_Delete", resourceCulture);
            }
        }
        
        internal static string Ratings_SelectAll {
            get {
                return ResourceManager.GetString("Ratings_SelectAll", resourceCulture);
            }
        }
        
        internal static string Ratings_SelectById {
            get {
                return ResourceManager.GetString("Ratings_SelectById", resourceCulture);
            }
        }
        
        internal static string Ratings_Insert {
            get {
                return ResourceManager.GetString("Ratings_Insert", resourceCulture);
            }
        }
        
        internal static string Ratings_Update {
            get {
                return ResourceManager.GetString("Ratings_Update", resourceCulture);
            }
        }
        
        internal static string Ratings_Delete {
            get {
                return ResourceManager.GetString("Ratings_Delete", resourceCulture);
            }
        }
        
        internal static string HotelRatings_SelectAll {
            get {
                return ResourceManager.GetString("HotelRatings_SelectAll", resourceCulture);
            }
        }
        
        internal static string HotelRatings_SelectById {
            get {
                return ResourceManager.GetString("HotelRatings_SelectById", resourceCulture);
            }
        }
        
        internal static string HotelRatings_SelectByHotelId {
            get {
                return ResourceManager.GetString("HotelRatings_SelectByHotelId", resourceCulture);
            }
        }
        
        internal static string HotelRatings_Insert {
            get {
                return ResourceManager.GetString("HotelRatings_Insert", resourceCulture);
            }
        }
        
        internal static string HotelRatings_Delete {
            get {
                return ResourceManager.GetString("HotelRatings_Delete", resourceCulture);
            }
        }
        
        internal static string HotelRatings_DeleteByHotelAndRating {
            get {
                return ResourceManager.GetString("HotelRatings_DeleteByHotelAndRating", resourceCulture);
            }
        }
        
        internal static string Comments_SelectAll {
            get {
                return ResourceManager.GetString("Comments_SelectAll", resourceCulture);
            }
        }
        
        internal static string Comments_SelectById {
            get {
                return ResourceManager.GetString("Comments_SelectById", resourceCulture);
            }
        }
        
        internal static string Comments_SelectByUserId {
            get {
                return ResourceManager.GetString("Comments_SelectByUserId", resourceCulture);
            }
        }
        
        internal static string Comments_Insert {
            get {
                return ResourceManager.GetString("Comments_Insert", resourceCulture);
            }
        }
        
        internal static string Comments_Update {
            get {
                return ResourceManager.GetString("Comments_Update", resourceCulture);
            }
        }
        
        internal static string Comments_Delete {
            get {
                return ResourceManager.GetString("Comments_Delete", resourceCulture);
            }
        }
        
        internal static string HotelComments_SelectAll {
            get {
                return ResourceManager.GetString("HotelComments_SelectAll", resourceCulture);
            }
        }
        
        internal static string HotelComments_SelectById {
            get {
                return ResourceManager.GetString("HotelComments_SelectById", resourceCulture);
            }
        }
        
        internal static string HotelComments_SelectByHotelId {
            get {
                return ResourceManager.GetString("HotelComments_SelectByHotelId", resourceCulture);
            }
        }
        
        internal static string HotelComments_Insert {
            get {
                return ResourceManager.GetString("HotelComments_Insert", resourceCulture);
            }
        }
        
        internal static string HotelComments_Delete {
            get {
                return ResourceManager.GetString("HotelComments_Delete", resourceCulture);
            }
        }
        
        internal static string HotelComments_DeleteByHotelAndComment {
            get {
                return ResourceManager.GetString("HotelComments_DeleteByHotelAndComment", resourceCulture);
            }
        }
        
        internal static string RentalCars_SelectAll {
            get {
                return ResourceManager.GetString("RentalCars_SelectAll", resourceCulture);
            }
        }
        
        internal static string RentalCars_SelectById {
            get {
                return ResourceManager.GetString("RentalCars_SelectById", resourceCulture);
            }
        }
        
        internal static string RentalCars_Insert {
            get {
                return ResourceManager.GetString("RentalCars_Insert", resourceCulture);
            }
        }
        
        internal static string RentalCars_Update {
            get {
                return ResourceManager.GetString("RentalCars_Update", resourceCulture);
            }
        }
        
        internal static string RentalCars_Delete {
            get {
                return ResourceManager.GetString("RentalCars_Delete", resourceCulture);
            }
        }
        
        internal static string HotelRentalCars_SelectAll {
            get {
                return ResourceManager.GetString("HotelRentalCars_SelectAll", resourceCulture);
            }
        }
        
        internal static string HotelRentalCars_SelectById {
            get {
                return ResourceManager.GetString("HotelRentalCars_SelectById", resourceCulture);
            }
        }
        
        internal static string HotelRentalCars_SelectByHotelId {
            get {
                return ResourceManager.GetString("HotelRentalCars_SelectByHotelId", resourceCulture);
            }
        }
        
        internal static string HotelRentalCars_Insert {
            get {
                return ResourceManager.GetString("HotelRentalCars_Insert", resourceCulture);
            }
        }
        
        internal static string HotelRentalCars_Delete {
            get {
                return ResourceManager.GetString("HotelRentalCars_Delete", resourceCulture);
            }
        }
        
        internal static string HotelRentalCars_DeleteByHotelAndRentalCar {
            get {
                return ResourceManager.GetString("HotelRentalCars_DeleteByHotelAndRentalCar", resourceCulture);
            }
        }
        
        internal static string RentalCarReservations_SelectAll {
            get {
                return ResourceManager.GetString("RentalCarReservations_SelectAll", resourceCulture);
            }
        }
        
        internal static string RentalCarReservations_SelectById {
            get {
                return ResourceManager.GetString("RentalCarReservations_SelectById", resourceCulture);
            }
        }
        
        internal static string RentalCarReservations_SelectByUserId {
            get {
                return ResourceManager.GetString("RentalCarReservations_SelectByUserId", resourceCulture);
            }
        }
        
        internal static string RentalCarReservations_Insert {
            get {
                return ResourceManager.GetString("RentalCarReservations_Insert", resourceCulture);
            }
        }
        
        internal static string RentalCarReservations_Update {
            get {
                return ResourceManager.GetString("RentalCarReservations_Update", resourceCulture);
            }
        }
        
        internal static string RentalCarReservations_Delete {
            get {
                return ResourceManager.GetString("RentalCarReservations_Delete", resourceCulture);
            }
        }
        
        internal static string TaxiCompanies_SelectAll {
            get {
                return ResourceManager.GetString("TaxiCompanies_SelectAll", resourceCulture);
            }
        }
        
        internal static string TaxiCompanies_SelectById {
            get {
                return ResourceManager.GetString("TaxiCompanies_SelectById", resourceCulture);
            }
        }
        
        internal static string TaxiCompanies_Insert {
            get {
                return ResourceManager.GetString("TaxiCompanies_Insert", resourceCulture);
            }
        }
        
        internal static string TaxiCompanies_Update {
            get {
                return ResourceManager.GetString("TaxiCompanies_Update", resourceCulture);
            }
        }
        
        internal static string TaxiCompanies_Delete {
            get {
                return ResourceManager.GetString("TaxiCompanies_Delete", resourceCulture);
            }
        }
        
        internal static string TaxiReservations_SelectAll {
            get {
                return ResourceManager.GetString("TaxiReservations_SelectAll", resourceCulture);
            }
        }
        
        internal static string TaxiReservations_SelectById {
            get {
                return ResourceManager.GetString("TaxiReservations_SelectById", resourceCulture);
            }
        }
        
        internal static string TaxiReservations_SelectByUserId {
            get {
                return ResourceManager.GetString("TaxiReservations_SelectByUserId", resourceCulture);
            }
        }
        
        internal static string TaxiReservations_Insert {
            get {
                return ResourceManager.GetString("TaxiReservations_Insert", resourceCulture);
            }
        }
        
        internal static string TaxiReservations_Update {
            get {
                return ResourceManager.GetString("TaxiReservations_Update", resourceCulture);
            }
        }
        
        internal static string TaxiReservations_Delete {
            get {
                return ResourceManager.GetString("TaxiReservations_Delete", resourceCulture);
            }
        }
        
        internal static string TaxiCompanyRatings_SelectAll {
            get {
                return ResourceManager.GetString("TaxiCompanyRatings_SelectAll", resourceCulture);
            }
        }
        
        internal static string TaxiCompanyRatings_SelectById {
            get {
                return ResourceManager.GetString("TaxiCompanyRatings_SelectById", resourceCulture);
            }
        }
        
        internal static string TaxiCompanyRatings_SelectByTaxiCompanyId {
            get {
                return ResourceManager.GetString("TaxiCompanyRatings_SelectByTaxiCompanyId", resourceCulture);
            }
        }
        
        internal static string TaxiCompanyRatings_Insert {
            get {
                return ResourceManager.GetString("TaxiCompanyRatings_Insert", resourceCulture);
            }
        }
        
        internal static string TaxiCompanyRatings_Delete {
            get {
                return ResourceManager.GetString("TaxiCompanyRatings_Delete", resourceCulture);
            }
        }
        
        internal static string TaxiCompanyRatings_DeleteByTaxiCompanyAndRating {
            get {
                return ResourceManager.GetString("TaxiCompanyRatings_DeleteByTaxiCompanyAndRating", resourceCulture);
            }
        }
        
        internal static string TaxiCompanyComments_SelectAll {
            get {
                return ResourceManager.GetString("TaxiCompanyComments_SelectAll", resourceCulture);
            }
        }
        
        internal static string TaxiCompanyComments_SelectById {
            get {
                return ResourceManager.GetString("TaxiCompanyComments_SelectById", resourceCulture);
            }
        }
        
        internal static string TaxiCompanyComments_SelectByTaxiCompanyId {
            get {
                return ResourceManager.GetString("TaxiCompanyComments_SelectByTaxiCompanyId", resourceCulture);
            }
        }
        
        internal static string TaxiCompanyComments_Insert {
            get {
                return ResourceManager.GetString("TaxiCompanyComments_Insert", resourceCulture);
            }
        }
        
        internal static string TaxiCompanyComments_Delete {
            get {
                return ResourceManager.GetString("TaxiCompanyComments_Delete", resourceCulture);
            }
        }
        
        internal static string TaxiCompanyComments_DeleteByTaxiCompanyAndComment {
            get {
                return ResourceManager.GetString("TaxiCompanyComments_DeleteByTaxiCompanyAndComment", resourceCulture);
            }
        }
        
        internal static string AIRecommendations_SelectAll {
            get {
                return ResourceManager.GetString("AIRecommendations_SelectAll", resourceCulture);
            }
        }
        
        internal static string AIRecommendations_SelectById {
            get {
                return ResourceManager.GetString("AIRecommendations_SelectById", resourceCulture);
            }
        }
        
        internal static string AIRecommendations_SelectByUserId {
            get {
                return ResourceManager.GetString("AIRecommendations_SelectByUserId", resourceCulture);
            }
        }
        
        internal static string AIRecommendations_Insert {
            get {
                return ResourceManager.GetString("AIRecommendations_Insert", resourceCulture);
            }
        }
        
        internal static string AIRecommendations_Update {
            get {
                return ResourceManager.GetString("AIRecommendations_Update", resourceCulture);
            }
        }
        
        internal static string AIRecommendations_Delete {
            get {
                return ResourceManager.GetString("AIRecommendations_Delete", resourceCulture);
            }
        }
        
        internal static string HotelReservations_SelectAll {
            get {
                return ResourceManager.GetString("HotelReservations_SelectAll", resourceCulture);
            }
        }
        
        internal static string Hotels_SelecyByCoutryName {
            get {
                return ResourceManager.GetString("Hotels_SelecyByCoutryName", resourceCulture);
            }
        }
        
        internal static string Hotels_SelectByEmail {
            get {
                return ResourceManager.GetString("Hotels_SelectByEmail", resourceCulture);
            }
        }
        
        internal static string Hotels_CheckHotelStatus {
            get {
                return ResourceManager.GetString("Hotels_CheckHotelStatus", resourceCulture);
            }
        }
        
        internal static string Hotels_UpdateHotelStatus {
            get {
                return ResourceManager.GetString("Hotels_UpdateHotelStatus", resourceCulture);
            }
        }
        
        internal static string Users_SelectUserByEmail {
            get {
                return ResourceManager.GetString("Users_SelectUserByEmail", resourceCulture);
            }
        }
        
        internal static string Users_SelectByRoleId {
            get {
                return ResourceManager.GetString("Users_SelectByRoleId", resourceCulture);
            }
        }
        
        internal static string Users_SelectByStatus {
            get {
                return ResourceManager.GetString("Users_SelectByStatus", resourceCulture);
            }
        }
        
        internal static string Users_UpdateStatus {
            get {
                return ResourceManager.GetString("Users_UpdateStatus", resourceCulture);
            }
        }
        
        internal static string Users_UpdateVerification {
            get {
                return ResourceManager.GetString("Users_UpdateVerification", resourceCulture);
            }
        }
        
        internal static string TaxiReservations_SelectAllWithUserName {
            get {
                return ResourceManager.GetString("TaxiReservations_SelectAllWithUserName", resourceCulture);
            }
        }
        
        internal static string TaxiReservations_SelectByUserIdWithUserName {
            get {
                return ResourceManager.GetString("TaxiReservations_SelectByUserIdWithUserName", resourceCulture);
            }
        }
        
        internal static string TaxiReservations_InsertSimple {
            get {
                return ResourceManager.GetString("TaxiReservations_InsertSimple", resourceCulture);
            }
        }
        
        internal static string TaxiReservations_UpdateSimple {
            get {
                return ResourceManager.GetString("TaxiReservations_UpdateSimple", resourceCulture);
            }
        }
    }
}
