//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SQLQueries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SQLQueries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DAL.SQLQueries", typeof(SQLQueries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM AIRecommendations
        ///WHERE Id = @Id.
        /// </summary>
        public static string AIRecommendations_Delete {
            get {
                return ResourceManager.GetString("AIRecommendations_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO AIRecommendations
        ///(
        ///    Id,
        ///    Prompt,
        ///    Reply,
        ///    PromptedUserId
        ///)
        ///VALUES
        ///(
        ///    @Id,
        ///    @Prompt,
        ///    @Reply,
        ///    @PromptedUserId
        ///).
        /// </summary>
        public static string AIRecommendations_Insert {
            get {
                return ResourceManager.GetString("AIRecommendations_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    Id,
        ///    Prompt,
        ///    Reply,
        ///    PromptedUserId
        ///FROM AIRecommendations.
        /// </summary>
        public static string AIRecommendations_SelectAll {
            get {
                return ResourceManager.GetString("AIRecommendations_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    Id,
        ///    Prompt,
        ///    Reply,
        ///    PromptedUserId
        ///FROM AIRecommendations
        ///WHERE Id = @Id.
        /// </summary>
        public static string AIRecommendations_SelectById {
            get {
                return ResourceManager.GetString("AIRecommendations_SelectById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    Id,
        ///    Prompt,
        ///    Reply,
        ///    PromptedUserId
        ///FROM AIRecommendations
        ///WHERE PromptedUserId = @PromptedUserId.
        /// </summary>
        public static string AIRecommendations_SelectByUserId {
            get {
                return ResourceManager.GetString("AIRecommendations_SelectByUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE AIRecommendations
        ///SET
        ///    Prompt = @Prompt,
        ///    Reply = @Reply,
        ///    PromptedUserId = @PromptedUserId
        ///WHERE Id = @Id.
        /// </summary>
        public static string AIRecommendations_Update {
            get {
                return ResourceManager.GetString("AIRecommendations_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM Comments
        ///WHERE Id = @Id.
        /// </summary>
        public static string Comments_Delete {
            get {
                return ResourceManager.GetString("Comments_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Comments
        ///(
        ///    Id,
        ///    Comment,
        ///    UserId,
        ///    Disabled,
        ///    CreatedAt,
        ///    UpdatedAt
        ///)
        ///VALUES
        ///(
        ///    @Id,
        ///    @Comment,
        ///    @UserId,
        ///    @Disabled,
        ///    @CreatedAt,
        ///    @UpdatedAt
        ///).
        /// </summary>
        public static string Comments_Insert {
            get {
                return ResourceManager.GetString("Comments_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    Id,
        ///    Comment,
        ///    UserId,
        ///    Disabled,
        ///    CreatedAt,
        ///    UpdatedAt
        ///FROM Comments.
        /// </summary>
        public static string Comments_SelectAll {
            get {
                return ResourceManager.GetString("Comments_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    Id,
        ///    Comment,
        ///    UserId,
        ///    Disabled,
        ///    CreatedAt,
        ///    UpdatedAt
        ///FROM Comments
        ///WHERE Id = @Id.
        /// </summary>
        public static string Comments_SelectById {
            get {
                return ResourceManager.GetString("Comments_SelectById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    Id,
        ///    Comment,
        ///    UserId,
        ///    Disabled,
        ///    CreatedAt,
        ///    UpdatedAt
        ///FROM Comments
        ///WHERE UserId = @UserId.
        /// </summary>
        public static string Comments_SelectByUserId {
            get {
                return ResourceManager.GetString("Comments_SelectByUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Comments
        ///SET
        ///    Comment = @Comment,
        ///    UserId = @UserId,
        ///    Disabled = @Disabled,
        ///    UpdatedAt = @UpdatedAt
        ///WHERE Id = @Id.
        /// </summary>
        public static string Comments_Update {
            get {
                return ResourceManager.GetString("Comments_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM Conveniences
        ///WHERE Id = @Id.
        /// </summary>
        public static string Conveniences_Delete {
            get {
                return ResourceManager.GetString("Conveniences_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Conveniences
        ///(
        ///    Id,
        ///    Name
        ///)
        ///VALUES
        ///(
        ///    @Id,
        ///    @Name
        ///).
        /// </summary>
        public static string Conveniences_Insert {
            get {
                return ResourceManager.GetString("Conveniences_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    Id,
        ///    Name
        ///FROM Conveniences.
        /// </summary>
        public static string Conveniences_SelectAll {
            get {
                return ResourceManager.GetString("Conveniences_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    Id,
        ///    Name
        ///FROM Conveniences
        ///WHERE Id = @Id.
        /// </summary>
        public static string Conveniences_SelectById {
            get {
                return ResourceManager.GetString("Conveniences_SelectById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Conveniences
        ///SET
        ///    Name = @Name
        ///WHERE Id = @Id.
        /// </summary>
        public static string Conveniences_Update {
            get {
                return ResourceManager.GetString("Conveniences_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM Currencies
        ///WHERE Id = @Id.
        /// </summary>
        public static string Currencies_Delete {
            get {
                return ResourceManager.GetString("Currencies_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Currencies
        ///(
        ///    Id,
        ///    Name,
        ///    Code
        ///)
        ///VALUES
        ///(
        ///    @Id,
        ///    @Name,
        ///    @Code
        ///).
        /// </summary>
        public static string Currencies_Insert {
            get {
                return ResourceManager.GetString("Currencies_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    Id,
        ///    Name,
        ///    Code
        ///FROM Currencies.
        /// </summary>
        public static string Currencies_SelectAll {
            get {
                return ResourceManager.GetString("Currencies_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    Id,
        ///    Name,
        ///    Code
        ///FROM Currencies
        ///WHERE Id = @Id.
        /// </summary>
        public static string Currencies_SelectById {
            get {
                return ResourceManager.GetString("Currencies_SelectById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Currencies
        ///SET
        ///    Name = @Name,
        ///    Code = @Code
        ///WHERE Id = @Id.
        /// </summary>
        public static string Currencies_Update {
            get {
                return ResourceManager.GetString("Currencies_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM HotelComments
        ///WHERE Id = @Id.
        /// </summary>
        public static string HotelComments_Delete {
            get {
                return ResourceManager.GetString("HotelComments_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM HotelComments
        ///WHERE HotelId = @HotelId
        ///  AND CommentId = @CommentId.
        /// </summary>
        public static string HotelComments_DeleteByHotelAndComment {
            get {
                return ResourceManager.GetString("HotelComments_DeleteByHotelAndComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO HotelComments
        ///(
        ///    Id,
        ///    HotelId,
        ///    CommentId
        ///)
        ///VALUES
        ///(
        ///    @Id,
        ///    @HotelId,
        ///    @CommentId
        ///).
        /// </summary>
        public static string HotelComments_Insert {
            get {
                return ResourceManager.GetString("HotelComments_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    Id,
        ///    HotelId,
        ///    CommentId
        ///FROM HotelComments.
        /// </summary>
        public static string HotelComments_SelectAll {
            get {
                return ResourceManager.GetString("HotelComments_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    Id,
        ///    HotelId,
        ///    CommentId
        ///FROM HotelComments
        ///WHERE HotelId = @HotelId.
        /// </summary>
        public static string HotelComments_SelectByHotelId {
            get {
                return ResourceManager.GetString("HotelComments_SelectByHotelId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    Id,
        ///    HotelId,
        ///    CommentId
        ///FROM HotelComments
        ///WHERE Id = @Id.
        /// </summary>
        public static string HotelComments_SelectById {
            get {
                return ResourceManager.GetString("HotelComments_SelectById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM HotelConveniences
        ///WHERE Id = @Id.
        /// </summary>
        public static string HotelConveniences_Delete {
            get {
                return ResourceManager.GetString("HotelConveniences_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM HotelConveniences
        ///WHERE HotelId = @HotelId
        ///  AND ConvenienceId = @ConvenienceId.
        /// </summary>
        public static string HotelConveniences_DeleteByHotelAndConvenience {
            get {
                return ResourceManager.GetString("HotelConveniences_DeleteByHotelAndConvenience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO HotelConveniences
        ///(
        ///    Id,
        ///    HotelId,
        ///    ConvenienceId
        ///)
        ///VALUES
        ///(
        ///    @Id,
        ///    @HotelId,
        ///    @ConvenienceId
        ///).
        /// </summary>
        public static string HotelConveniences_Insert {
            get {
                return ResourceManager.GetString("HotelConveniences_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    Id,
        ///    HotelId,
        ///    ConvenienceId
        ///FROM HotelConveniences.
        /// </summary>
        public static string HotelConveniences_SelectAll {
            get {
                return ResourceManager.GetString("HotelConveniences_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    hc.Id,
        ///    hc.HotelId,
        ///    hc.ConvenienceId
        ///FROM HotelConveniences hc
        ///WHERE hc.HotelId = @HotelId.
        /// </summary>
        public static string HotelConveniences_SelectByHotelId {
            get {
                return ResourceManager.GetString("HotelConveniences_SelectByHotelId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    Id,
        ///    HotelId,
        ///    ConvenienceId
        ///FROM HotelConveniences
        ///WHERE Id = @Id.
        /// </summary>
        public static string HotelConveniences_SelectById {
            get {
                return ResourceManager.GetString("HotelConveniences_SelectById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM HotelPayments
        ///WHERE Id = @Id.
        /// </summary>
        public static string HotelPayments_Delete {
            get {
                return ResourceManager.GetString("HotelPayments_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO HotelPayments
        ///(
        ///    Id,
        ///    UserId,
        ///    RoomId,
        ///    CurrencyId,
        ///    Amount,
        ///    CreatedAt
        ///)
        ///VALUES
        ///(
        ///    @Id,
        ///    @UserId,
        ///    @RoomId,
        ///    @CurrencyId,
        ///    @Amount,
        ///    @CreatedAt
        ///).
        /// </summary>
        public static string HotelPayments_Insert {
            get {
                return ResourceManager.GetString("HotelPayments_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    Id,
        ///    UserId,
        ///    RoomId,
        ///    CurrencyId,
        ///    Amount,
        ///    CreatedAt
        ///FROM HotelPayments.
        /// </summary>
        public static string HotelPayments_SelectAll {
            get {
                return ResourceManager.GetString("HotelPayments_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    Id,
        ///    UserId,
        ///    RoomId,
        ///    CurrencyId,
        ///    Amount,
        ///    CreatedAt
        ///FROM HotelPayments
        ///WHERE Id = @Id.
        /// </summary>
        public static string HotelPayments_SelectById {
            get {
                return ResourceManager.GetString("HotelPayments_SelectById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    Id,
        ///    UserId,
        ///    RoomId,
        ///    CurrencyId,
        ///    Amount,
        ///    CreatedAt
        ///FROM HotelPayments
        ///WHERE UserId = @UserId.
        /// </summary>
        public static string HotelPayments_SelectByUserId {
            get {
                return ResourceManager.GetString("HotelPayments_SelectByUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM HotelRatings
        ///WHERE Id = @Id.
        /// </summary>
        public static string HotelRatings_Delete {
            get {
                return ResourceManager.GetString("HotelRatings_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM HotelRatings
        ///WHERE HotelId = @HotelId
        ///  AND RatingId = @RatingId.
        /// </summary>
        public static string HotelRatings_DeleteByHotelAndRating {
            get {
                return ResourceManager.GetString("HotelRatings_DeleteByHotelAndRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO HotelRatings
        ///(
        ///    Id,
        ///    HotelId,
        ///    RatingId
        ///)
        ///VALUES
        ///(
        ///    @Id,
        ///    @HotelId,
        ///    @RatingId
        ///).
        /// </summary>
        public static string HotelRatings_Insert {
            get {
                return ResourceManager.GetString("HotelRatings_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    Id,
        ///    HotelId,
        ///    RatingId
        ///FROM HotelRatings.
        /// </summary>
        public static string HotelRatings_SelectAll {
            get {
                return ResourceManager.GetString("HotelRatings_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    Id,
        ///    HotelId,
        ///    RatingId
        ///FROM HotelRatings
        ///WHERE HotelId = @HotelId.
        /// </summary>
        public static string HotelRatings_SelectByHotelId {
            get {
                return ResourceManager.GetString("HotelRatings_SelectByHotelId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    Id,
        ///    HotelId,
        ///    RatingId
        ///FROM HotelRatings
        ///WHERE Id = @Id.
        /// </summary>
        public static string HotelRatings_SelectById {
            get {
                return ResourceManager.GetString("HotelRatings_SelectById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM HotelRentalCars
        ///WHERE Id = @Id.
        /// </summary>
        public static string HotelRentalCars_Delete {
            get {
                return ResourceManager.GetString("HotelRentalCars_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM HotelRentalCars
        ///WHERE HotelId = @HotelId
        ///  AND RentalCarId = @RentalCarId.
        /// </summary>
        public static string HotelRentalCars_DeleteByHotelAndRentalCar {
            get {
                return ResourceManager.GetString("HotelRentalCars_DeleteByHotelAndRentalCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO HotelRentalCars
        ///(
        ///    Id,
        ///    HotelId,
        ///    RentalCarId
        ///)
        ///VALUES
        ///(
        ///    @Id,
        ///    @HotelId,
        ///    @RentalCarId
        ///).
        /// </summary>
        public static string HotelRentalCars_Insert {
            get {
                return ResourceManager.GetString("HotelRentalCars_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    Id,
        ///    HotelId,
        ///    RentalCarId
        ///FROM HotelRentalCars.
        /// </summary>
        public static string HotelRentalCars_SelectAll {
            get {
                return ResourceManager.GetString("HotelRentalCars_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    Id,
        ///    HotelId,
        ///    RentalCarId
        ///FROM HotelRentalCars
        ///WHERE HotelId = @HotelId.
        /// </summary>
        public static string HotelRentalCars_SelectByHotelId {
            get {
                return ResourceManager.GetString("HotelRentalCars_SelectByHotelId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    Id,
        ///    HotelId,
        ///    RentalCarId
        ///FROM HotelRentalCars
        ///WHERE Id = @Id.
        /// </summary>
        public static string HotelRentalCars_SelectById {
            get {
                return ResourceManager.GetString("HotelRentalCars_SelectById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM HotelReservation
        ///WHERE Id = @Id.
        /// </summary>
        public static string HotelReservations_Delete {
            get {
                return ResourceManager.GetString("HotelReservations_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO HotelReservation
        ///(
        ///    Id,
        ///    HotelId,
        ///    UserId,
        ///    RoomId,
        ///    CheckIn,
        ///    CheckOut,
        ///    CreatedAt,
        ///    UpdatedAt
        ///)
        ///VALUES
        ///(
        ///    @Id,
        ///    @HotelId,
        ///    @UserId,
        ///    @RoomId,
        ///    @CheckIn,
        ///    @CheckOut,
        ///    @CreatedAt,
        ///    @UpdatedAt
        ///).
        /// </summary>
        public static string HotelReservations_Insert {
            get {
                return ResourceManager.GetString("HotelReservations_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///    res.[Id],
        ///    res.[CheckIn],
        ///    res.[CheckOut],
        ///
        ///    h.[Id] AS HotelId,
        ///    h.[Name],
        ///    h.[Country],
        ///    h.[City],
        ///    h.[Street],
        ///    h.[PostalCode],
        ///    h.[PhoneNumber],
        ///    h.[Email],
        ///
        ///    u.[Id] AS UserId,
        ///    u.[Email],
        ///    u.[FirstName],
        ///    u.[LastName],
        ///
        ///    rm.[Id] AS RoomId,
        ///    rm.[Description],
        ///    rm.[Price],
        ///    rm.[RoomNo],
        ///    rm.[Floor],
        ///    rm.[BedCount],
        ///    rm.[Capacity]
        ///
        ///FROM [HotelReservation] res
        ///INNER JOIN [Hotels] h ON res.[HotelID] = h.[Id [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HotelReservations_SelectAll {
            get {
                return ResourceManager.GetString("HotelReservations_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    Id,
        ///    HotelId,
        ///    UserId,
        ///    RoomId,
        ///    CheckIn,
        ///    CheckOut,
        ///    CreatedAt,
        ///    UpdatedAt
        ///FROM HotelReservation
        ///WHERE HotelId = @HotelId.
        /// </summary>
        public static string HotelReservations_SelectByHotelId {
            get {
                return ResourceManager.GetString("HotelReservations_SelectByHotelId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///    res.[Id],
        ///    res.[CheckIn],
        ///    res.[CheckOut],
        ///
        ///    h.[Id] AS HotelId,
        ///    h.[Name],
        ///    h.[Country],
        ///    h.[City],
        ///    h.[Street],
        ///    h.[PostalCode],
        ///    h.[PhoneNumber],
        ///    h.[Email],
        ///
        ///    u.[Id] AS UserId,
        ///    u.[Email],
        ///    u.[FirstName],
        ///    u.[LastName],
        ///
        ///    rm.[Id] AS RoomId,
        ///    rm.[Description],
        ///    rm.[Price],
        ///    rm.[RoomNo],
        ///    rm.[Floor],
        ///    rm.[BedCount],
        ///    rm.[Capacity]
        ///
        ///FROM [HotelReservation] res
        ///INNER JOIN [Hotels] h ON res.[HotelID] = h.[Id [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HotelReservations_SelectById {
            get {
                return ResourceManager.GetString("HotelReservations_SelectById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///    res.[Id],
        ///    res.[CheckIn],
        ///    res.[CheckOut],
        ///
        ///    h.[Id] AS HotelId,
        ///    h.[Name],
        ///    h.[Country],
        ///    h.[City],
        ///    h.[Street],
        ///    h.[PostalCode],
        ///    h.[PhoneNumber],
        ///    h.[Email],
        ///
        ///    u.[Id] AS UserId,
        ///    u.[Email],
        ///    u.[FirstName],
        ///    u.[LastName],
        ///
        ///    rm.[Id] AS RoomId,
        ///    rm.[Description],
        ///    rm.[Price],
        ///    rm.[RoomNo],
        ///    rm.[Floor],
        ///    rm.[BedCount],
        ///    rm.[Capacity]
        ///
        ///FROM [HotelReservation] res
        ///INNER JOIN [Hotels] h ON res.[HotelID] = h.[Id [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HotelReservations_SelectByUserId {
            get {
                return ResourceManager.GetString("HotelReservations_SelectByUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE HotelReservation
        ///SET
        ///    HotelId = @HotelId,
        ///    UserId = @UserId,
        ///    RoomId = @RoomId,
        ///    CheckIn = @CheckIn,
        ///    CheckOut = @CheckOut,
        ///    UpdatedAt = @UpdatedAt
        ///WHERE Id = @Id.
        /// </summary>
        public static string HotelReservations_Update {
            get {
                return ResourceManager.GetString("HotelReservations_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM HotelRoomConveniences
        ///WHERE Id = @Id.
        /// </summary>
        public static string HotelRoomConveniences_Delete {
            get {
                return ResourceManager.GetString("HotelRoomConveniences_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM HotelRoomConveniences
        ///WHERE HotelRoomId = @HotelRoomId
        ///  AND ConvenienceId = @ConvenienceId.
        /// </summary>
        public static string HotelRoomConveniences_DeleteByRoomAndConvenience {
            get {
                return ResourceManager.GetString("HotelRoomConveniences_DeleteByRoomAndConvenience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO HotelRoomConveniences
        ///(
        ///    Id,
        ///    HotelRoomId,
        ///    ConvenienceId
        ///)
        ///VALUES
        ///(
        ///    @Id,
        ///    @HotelRoomId,
        ///    @ConvenienceId
        ///).
        /// </summary>
        public static string HotelRoomConveniences_Insert {
            get {
                return ResourceManager.GetString("HotelRoomConveniences_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    Id,
        ///    HotelRoomId,
        ///    ConvenienceId
        ///FROM HotelRoomConveniences.
        /// </summary>
        public static string HotelRoomConveniences_SelectAll {
            get {
                return ResourceManager.GetString("HotelRoomConveniences_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    Id,
        ///    HotelRoomId,
        ///    ConvenienceId
        ///FROM HotelRoomConveniences
        ///WHERE Id = @Id.
        /// </summary>
        public static string HotelRoomConveniences_SelectById {
            get {
                return ResourceManager.GetString("HotelRoomConveniences_SelectById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    Id,
        ///    HotelRoomId,
        ///    ConvenienceId
        ///FROM HotelRoomConveniences
        ///WHERE HotelRoomId = @HotelRoomId.
        /// </summary>
        public static string HotelRoomConveniences_SelectByRoomId {
            get {
                return ResourceManager.GetString("HotelRoomConveniences_SelectByRoomId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM HotelRooms
        ///WHERE Id = @Id.
        /// </summary>
        public static string HotelRooms_Delete {
            get {
                return ResourceManager.GetString("HotelRooms_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO HotelRooms
        ///(
        ///    Id,
        ///    HotelId,
        ///    Description,
        ///    Price,
        ///    RoomNo,
        ///    Floor,
        ///    BedCount,
        ///    Capacity,
        ///    CreatedAt,
        ///    UpdatedAt
        ///)
        ///VALUES
        ///(
        ///    @Id,
        ///    @HotelId,
        ///    @Description,
        ///    @Price,
        ///    @RoomNo,
        ///    @Floor,
        ///    @BedCount,
        ///    @Capacity,
        ///    @CreatedAt,
        ///    @UpdatedAt
        ///).
        /// </summary>
        public static string HotelRooms_Insert {
            get {
                return ResourceManager.GetString("HotelRooms_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///		SELECT 
        ///		
        ///		res.[Id],
        ///        res.[Description],
        ///        res.[Price],
        ///        res.[RoomNo],
        ///        res.[Floor],
        ///        res.[BedCount],
        ///        res.[Capacity],
        ///		
        ///		hotel.[Id] AS HotelId,
        ///		hotel.[Name]
        ///
        ///        FROM [HotelRooms] res
        ///        INNER JOIN [Hotels] hotel ON res.[hotelId] = hotel.[Id];
        ///  .
        /// </summary>
        public static string HotelRooms_SelectAll {
            get {
                return ResourceManager.GetString("HotelRooms_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///		
        ///		res.[Id],
        ///        res.[Description],
        ///        res.[Price],
        ///        res.[RoomNo],
        ///        res.[Floor],
        ///        res.[BedCount],
        ///        res.[Capacity],
        ///		
        ///		hotel.[Id] AS HotelId,
        ///		hotel.[Name]
        ///
        ///        FROM [HotelRooms] res
        ///        INNER JOIN [Hotels] hotel ON res.[HotelId] = hotel.[Id]
        ///	    WHERE hotel.[Id] = @Id.
        /// </summary>
        public static string HotelRooms_SelectByHotelId {
            get {
                return ResourceManager.GetString("HotelRooms_SelectByHotelId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///		
        ///		res.[Id],
        ///        res.[Description],
        ///        res.[Price],
        ///        res.[RoomNo],
        ///        res.[Floor],
        ///        res.[BedCount],
        ///        res.[Capacity],
        ///		
        ///		hotel.[Id] AS HotelId,
        ///		hotel.[Name]
        ///
        ///        FROM [HotelRooms] res
        ///        INNER JOIN [Hotels] hotel ON res.[hotelId] = hotel.[Id]
        ///        WHERE res.[Id] = @Id;.
        /// </summary>
        public static string HotelRooms_SelectById {
            get {
                return ResourceManager.GetString("HotelRooms_SelectById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE HotelRooms
        ///SET
        ///    HotelId = @HotelId,
        ///    Description = @Description,
        ///    Price = @Price,
        ///    RoomNo = @RoomNo,
        ///    Floor = @Floor,
        ///    BedCount = @BedCount,
        ///    Capacity = @Capacity,
        ///    UpdatedAt = @UpdatedAt
        ///WHERE Id = @Id.
        /// </summary>
        public static string HotelRooms_Update {
            get {
                return ResourceManager.GetString("HotelRooms_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    Status
        ///FROM Hotels
        ///WHERE Id = @Id.
        /// </summary>
        public static string Hotels_CheckHotelStatus {
            get {
                return ResourceManager.GetString("Hotels_CheckHotelStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM Hotels
        ///WHERE Id = @Id.
        /// </summary>
        public static string Hotels_Delete {
            get {
                return ResourceManager.GetString("Hotels_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Hotels
        ///(
        ///    Id,
        ///    Name,
        ///    Country,
        ///    City,
        ///    Street,
        ///    PostalCode,
        ///    PhoneNumber,
        ///    Email,
        ///    Status,
        ///    Approved,
        ///    CreatedAt,
        ///    UpdatedAt
        ///)
        ///VALUES
        ///(
        ///    @Id,
        ///    @Name,
        ///    @Country,
        ///    @City,
        ///    @Street,
        ///    @PostalCode,
        ///    @PhoneNumber,
        ///    @Email,
        ///    @Status,
        ///    @Approved,
        ///    @CreatedAt,
        ///    @UpdatedAt
        ///).
        /// </summary>
        public static string Hotels_Insert {
            get {
                return ResourceManager.GetString("Hotels_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    Id,
        ///    Name,
        ///    Country,
        ///    City,
        ///    Street,
        ///    PostalCode,
        ///    PhoneNumber,
        ///    Email,
        ///    Status,
        ///    Approved,
        ///    CreatedAt,
        ///    UpdatedAt
        ///FROM Hotels.
        /// </summary>
        public static string Hotels_SelectAll {
            get {
                return ResourceManager.GetString("Hotels_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    Id,
        ///    Name,
        ///    Country,
        ///    City,
        ///    Street,
        ///    PostalCode,
        ///    PhoneNumber,
        ///    Email,
        ///    Status,
        ///    Approved,
        ///    CreatedAt,
        ///    UpdatedAt
        ///FROM Hotels
        ///WHERE Email = @Email.
        /// </summary>
        public static string Hotels_SelectByEmail {
            get {
                return ResourceManager.GetString("Hotels_SelectByEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    Id,
        ///    Name,
        ///    Country,
        ///    City,
        ///    Street,
        ///    PostalCode,
        ///    PhoneNumber,
        ///    Email,
        ///    Status,
        ///    Approved,
        ///    CreatedAt,
        ///    UpdatedAt
        ///FROM Hotels
        ///WHERE Id = @Id.
        /// </summary>
        public static string Hotels_SelectById {
            get {
                return ResourceManager.GetString("Hotels_SelectById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    Id,
        ///    Name,
        ///    Country,
        ///    City,
        ///    Street,
        ///    PostalCode,
        ///    PhoneNumber,
        ///    Email,
        ///    Status,
        ///    Approved,
        ///    CreatedAt,
        ///    UpdatedAt
        ///FROM Hotels
        ///WHERE Country = @Country.
        /// </summary>
        public static string Hotels_SelecyByCoutryName {
            get {
                return ResourceManager.GetString("Hotels_SelecyByCoutryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Hotels
        ///SET
        ///    Name = @Name,
        ///    Country = @Country,
        ///    City = @City,
        ///    Street = @Street,
        ///    PostalCode = @PostalCode,
        ///    PhoneNumber = @PhoneNumber,
        ///    Email = @Email,
        ///    Status = @Status,
        ///    Approved = @Approved,
        ///    UpdatedAt = @UpdatedAt
        ///WHERE Id = @Id.
        /// </summary>
        public static string Hotels_Update {
            get {
                return ResourceManager.GetString("Hotels_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Hotels
        ///SET
        ///    Status = 1
        ///
        ///WHERE Id = @Id.
        /// </summary>
        public static string Hotels_UpdateHotelStatus {
            get {
                return ResourceManager.GetString("Hotels_UpdateHotelStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM Ratings
        ///WHERE Id = @Id.
        /// </summary>
        public static string Ratings_Delete {
            get {
                return ResourceManager.GetString("Ratings_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Ratings
        ///(
        ///    Id,
        ///    Disabled,
        ///    Rating,
        ///    CreatedAt
        ///)
        ///VALUES
        ///(
        ///    @Id,
        ///    @Disabled,
        ///    @Rating,
        ///    @CreatedAt
        ///).
        /// </summary>
        public static string Ratings_Insert {
            get {
                return ResourceManager.GetString("Ratings_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    Id,
        ///    Disabled,
        ///    Rating,
        ///    CreatedAt
        ///FROM Ratings.
        /// </summary>
        public static string Ratings_SelectAll {
            get {
                return ResourceManager.GetString("Ratings_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    Id,
        ///    Disabled,
        ///    Rating,
        ///    CreatedAt
        ///FROM Ratings
        ///WHERE Id = @Id.
        /// </summary>
        public static string Ratings_SelectById {
            get {
                return ResourceManager.GetString("Ratings_SelectById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Ratings
        ///SET
        ///    Disabled = @Disabled,
        ///    Rating = @Rating
        ///WHERE Id = @Id.
        /// </summary>
        public static string Ratings_Update {
            get {
                return ResourceManager.GetString("Ratings_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM RentalCarReservation
        ///WHERE Id = @Id.
        /// </summary>
        public static string RentalCarReservations_Delete {
            get {
                return ResourceManager.GetString("RentalCarReservations_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO RentalCarReservation
        ///(
        ///    Id,
        ///    UserId,
        ///    CarId,
        ///    UseFrom,
        ///    UseTo,
        ///    CreatedAt,
        ///    UpdatedAt
        ///)
        ///VALUES
        ///(
        ///    @Id,
        ///    @UserId,
        ///    @CarId,
        ///    @UseFrom,
        ///    @UseTo,
        ///    @CreatedAt,
        ///    @UpdatedAt
        ///).
        /// </summary>
        public static string RentalCarReservations_Insert {
            get {
                return ResourceManager.GetString("RentalCarReservations_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///    res.[Id],
        ///    res.[UseFrom],
        ///    res.[UseTo],
        ///
        ///    c.[Id] AS CarId,
        ///    c.[Brand],
        ///    c.[Model],
        ///    c.[Kilometers],
        ///
        ///    u.[Id] AS UserId,
        ///    u.[Email],
        ///    u.[FirstName],
        ///    u.[LastName]
        ///
        ///FROM [RentalCarReservation] res
        ///INNER JOIN [RentalCars] c ON res.[CarID] = c.[Id]
        ///INNER JOIN [Users] u ON res.[UserID] = u.[Id];.
        /// </summary>
        public static string RentalCarReservations_SelectAll {
            get {
                return ResourceManager.GetString("RentalCarReservations_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///    res.[Id],
        ///    res.[UseFrom],
        ///    res.[UseTo],
        ///
        ///    c.[Id] AS CarId,
        ///    c.[Brand],
        ///    c.[Model],
        ///    c.[Kilometers],
        ///
        ///    u.[Id] AS UserId,
        ///    u.[Email],
        ///    u.[FirstName],
        ///    u.[LastName]
        ///
        ///FROM [RentalCarReservation] res
        ///INNER JOIN [RentalCars] c ON res.[CarID] = c.[Id]
        ///INNER JOIN [Users] u ON res.[UserID] = u.[Id]
        ///
        ///WHERE res.[Id] = @Id.
        /// </summary>
        public static string RentalCarReservations_SelectById {
            get {
                return ResourceManager.GetString("RentalCarReservations_SelectById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///    res.[Id],
        ///    res.[UseFrom],
        ///    res.[UseTo],
        ///
        ///    c.[Id] AS CarId,
        ///    c.[Brand],
        ///    c.[Model],
        ///    c.[Kilometers],
        ///
        ///    u.[Id] AS UserId,
        ///    u.[Email],
        ///    u.[FirstName],
        ///    u.[LastName]
        ///
        ///FROM [RentalCarReservation] res
        ///INNER JOIN [RentalCars] c ON res.[CarID] = c.[Id]
        ///INNER JOIN [Users] u ON res.[UserID] = u.[Id]
        ///
        ///WHERE u.[Id] = @Id.
        /// </summary>
        public static string RentalCarReservations_SelectByUserId {
            get {
                return ResourceManager.GetString("RentalCarReservations_SelectByUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE RentalCarReservation
        ///SET
        ///    UserId = @UserId,
        ///    CarId = @CarId,
        ///    UseFrom = @UseFrom,
        ///    UseTo = @UseTo,
        ///    UpdatedAt = @UpdatedAt
        ///WHERE Id = @Id.
        /// </summary>
        public static string RentalCarReservations_Update {
            get {
                return ResourceManager.GetString("RentalCarReservations_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM RentalCars
        ///WHERE Id = @Id.
        /// </summary>
        public static string RentalCars_Delete {
            get {
                return ResourceManager.GetString("RentalCars_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO RentalCars
        ///(
        ///    Id,
        ///    Brand,
        ///    Model,
        ///    Kilometers
        ///)
        ///VALUES
        ///(
        ///    @Id,
        ///    @Brand,
        ///    @Model,
        ///    @Kilometers
        ///).
        /// </summary>
        public static string RentalCars_Insert {
            get {
                return ResourceManager.GetString("RentalCars_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    Id,
        ///    Brand,
        ///    Model,
        ///    Kilometers
        ///FROM RentalCars.
        /// </summary>
        public static string RentalCars_SelectAll {
            get {
                return ResourceManager.GetString("RentalCars_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    Id,
        ///    Brand,
        ///    Model,
        ///    Kilometers
        ///FROM RentalCars
        ///WHERE Id = @Id.
        /// </summary>
        public static string RentalCars_SelectById {
            get {
                return ResourceManager.GetString("RentalCars_SelectById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE RentalCars
        ///SET
        ///    Brand = @Brand,
        ///    Model = @Model,
        ///    Kilometers = @Kilometers
        ///WHERE Id = @Id.
        /// </summary>
        public static string RentalCars_Update {
            get {
                return ResourceManager.GetString("RentalCars_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM TaxiCompany
        ///WHERE Id = @Id.
        /// </summary>
        public static string TaxiCompanies_Delete {
            get {
                return ResourceManager.GetString("TaxiCompanies_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO TaxiCompany
        ///(
        ///    Id,
        ///    Name,
        ///    Country,
        ///    City,
        ///    Street,
        ///    PostalCode,
        ///    PhoneNumber,
        ///    Email,
        ///    Status,
        ///    Approved,
        ///    CreatedAt,
        ///    UpdatedAt
        ///)
        ///VALUES
        ///(
        ///    @Id,
        ///    @Name,
        ///    @Country,
        ///    @City,
        ///    @Street,
        ///    @PostalCode,
        ///    @PhoneNumber,
        ///    @Email,
        ///    @Status,
        ///    @Approved,
        ///    @CreatedAt,
        ///    @UpdatedAt
        ///).
        /// </summary>
        public static string TaxiCompanies_Insert {
            get {
                return ResourceManager.GetString("TaxiCompanies_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    Id,
        ///    Name,
        ///    Country,
        ///    City,
        ///    Street,
        ///    PostalCode,
        ///    PhoneNumber,
        ///    Email,
        ///    Status,
        ///    Approved,
        ///    CreatedAt,
        ///    UpdatedAt
        ///FROM TaxiCompany.
        /// </summary>
        public static string TaxiCompanies_SelectAll {
            get {
                return ResourceManager.GetString("TaxiCompanies_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    Id,
        ///    Name,
        ///    Country,
        ///    City,
        ///    Street,
        ///    PostalCode,
        ///    PhoneNumber,
        ///    Email,
        ///    Status,
        ///    Approved,
        ///    CreatedAt,
        ///    UpdatedAt
        ///FROM TaxiCompany
        ///WHERE Id = @Id.
        /// </summary>
        public static string TaxiCompanies_SelectById {
            get {
                return ResourceManager.GetString("TaxiCompanies_SelectById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE TaxiCompany
        ///SET
        ///    Name = @Name,
        ///    Country = @Country,
        ///    City = @City,
        ///    Street = @Street,
        ///    PostalCode = @PostalCode,
        ///    PhoneNumber = @PhoneNumber,
        ///    Email = @Email,
        ///    Status = @Status,
        ///    Approved = @Approved,
        ///    UpdatedAt = @UpdatedAt
        ///WHERE Id = @Id.
        /// </summary>
        public static string TaxiCompanies_Update {
            get {
                return ResourceManager.GetString("TaxiCompanies_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM TaxiCompanyComments
        ///WHERE Id = @Id.
        /// </summary>
        public static string TaxiCompanyComments_Delete {
            get {
                return ResourceManager.GetString("TaxiCompanyComments_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM TaxiCompanyComments
        ///WHERE TaxiCompanyId = @TaxiCompanyId
        ///  AND CommentId = @CommentId.
        /// </summary>
        public static string TaxiCompanyComments_DeleteByTaxiCompanyAndComment {
            get {
                return ResourceManager.GetString("TaxiCompanyComments_DeleteByTaxiCompanyAndComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO TaxiCompanyComments
        ///(
        ///    Id,
        ///    TaxiCompanyId,
        ///    CommentId
        ///)
        ///VALUES
        ///(
        ///    @Id,
        ///    @TaxiCompanyId,
        ///    @CommentId
        ///).
        /// </summary>
        public static string TaxiCompanyComments_Insert {
            get {
                return ResourceManager.GetString("TaxiCompanyComments_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    Id,
        ///    TaxiCompanyId,
        ///    CommentId
        ///FROM TaxiCompanyComments.
        /// </summary>
        public static string TaxiCompanyComments_SelectAll {
            get {
                return ResourceManager.GetString("TaxiCompanyComments_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    Id,
        ///    TaxiCompanyId,
        ///    CommentId
        ///FROM TaxiCompanyComments
        ///WHERE Id = @Id.
        /// </summary>
        public static string TaxiCompanyComments_SelectById {
            get {
                return ResourceManager.GetString("TaxiCompanyComments_SelectById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    Id,
        ///    TaxiCompanyId,
        ///    CommentId
        ///FROM TaxiCompanyComments
        ///WHERE TaxiCompanyId = @TaxiCompanyId.
        /// </summary>
        public static string TaxiCompanyComments_SelectByTaxiCompanyId {
            get {
                return ResourceManager.GetString("TaxiCompanyComments_SelectByTaxiCompanyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM TaxiCompanyRatings
        ///WHERE Id = @Id.
        /// </summary>
        public static string TaxiCompanyRatings_Delete {
            get {
                return ResourceManager.GetString("TaxiCompanyRatings_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM TaxiCompanyRatings
        ///WHERE TaxiCompanyId = @TaxiCompanyId
        ///  AND RatingId = @RatingId.
        /// </summary>
        public static string TaxiCompanyRatings_DeleteByTaxiCompanyAndRating {
            get {
                return ResourceManager.GetString("TaxiCompanyRatings_DeleteByTaxiCompanyAndRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO TaxiCompanyRatings
        ///(
        ///    Id,
        ///    TaxiCompanyId,
        ///    RatingId
        ///)
        ///VALUES
        ///(
        ///    @Id,
        ///    @TaxiCompanyId,
        ///    @RatingId
        ///).
        /// </summary>
        public static string TaxiCompanyRatings_Insert {
            get {
                return ResourceManager.GetString("TaxiCompanyRatings_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    Id,
        ///    TaxiCompanyId,
        ///    RatingId
        ///FROM TaxiCompanyRatings.
        /// </summary>
        public static string TaxiCompanyRatings_SelectAll {
            get {
                return ResourceManager.GetString("TaxiCompanyRatings_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    Id,
        ///    TaxiCompanyId,
        ///    RatingId
        ///FROM TaxiCompanyRatings
        ///WHERE Id = @Id.
        /// </summary>
        public static string TaxiCompanyRatings_SelectById {
            get {
                return ResourceManager.GetString("TaxiCompanyRatings_SelectById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    Id,
        ///    TaxiCompanyId,
        ///    RatingId
        ///FROM TaxiCompanyRatings
        ///WHERE TaxiCompanyId = @TaxiCompanyId.
        /// </summary>
        public static string TaxiCompanyRatings_SelectByTaxiCompanyId {
            get {
                return ResourceManager.GetString("TaxiCompanyRatings_SelectByTaxiCompanyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM TaxiReservation
        ///WHERE Id = @Id.
        /// </summary>
        public static string TaxiReservations_Delete {
            get {
                return ResourceManager.GetString("TaxiReservations_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO TaxiReservation
        ///(
        ///    Id,
        ///    TaxiCompanyId,
        ///    UserId,
        ///    PickupAddress,
        ///    DestinationAddress,
        ///    Time,
        ///    CreatedAt,
        ///    UpdatedAt
        ///)
        ///VALUES
        ///(
        ///    @Id,
        ///    @TaxiCompanyId,
        ///    @UserId,
        ///    @PickupAddress,
        ///    @DestinationAddress,
        ///    @Time,
        ///    @CreatedAt,
        ///    @UpdatedAt
        ///).
        /// </summary>
        public static string TaxiReservations_Insert {
            get {
                return ResourceManager.GetString("TaxiReservations_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    Id,
        ///    TaxiCompanyId,
        ///    UserId,
        ///    PickupAddress,
        ///    DestinationAddress,
        ///    Time,
        ///    CreatedAt,
        ///    UpdatedAt
        ///FROM TaxiReservation.
        /// </summary>
        public static string TaxiReservations_SelectAll {
            get {
                return ResourceManager.GetString("TaxiReservations_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    Id,
        ///    TaxiCompanyId,
        ///    UserId,
        ///    PickupAddress,
        ///    DestinationAddress,
        ///    Time,
        ///    CreatedAt,
        ///    UpdatedAt
        ///FROM TaxiReservation
        ///WHERE Id = @Id.
        /// </summary>
        public static string TaxiReservations_SelectById {
            get {
                return ResourceManager.GetString("TaxiReservations_SelectById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    Id,
        ///    TaxiCompanyId,
        ///    UserId,
        ///    PickupAddress,
        ///    DestinationAddress,
        ///    Time,
        ///    CreatedAt,
        ///    UpdatedAt
        ///FROM TaxiReservation
        ///WHERE UserId = @UserId.
        /// </summary>
        public static string TaxiReservations_SelectByUserId {
            get {
                return ResourceManager.GetString("TaxiReservations_SelectByUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE TaxiReservation
        ///SET
        ///    TaxiCompanyId = @TaxiCompanyId,
        ///    UserId = @UserId,
        ///    PickupAddress = @PickupAddress,
        ///    DestinationAddress = @DestinationAddress,
        ///    Time = @Time,
        ///    UpdatedAt = @UpdatedAt
        ///WHERE Id = @Id.
        /// </summary>
        public static string TaxiReservations_Update {
            get {
                return ResourceManager.GetString("TaxiReservations_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM Users
        ///WHERE Id = @Id.
        /// </summary>
        public static string Users_Delete {
            get {
                return ResourceManager.GetString("Users_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT CAST(CASE
        ///WHEN EXISTS (
        ///    SELECT 1
        ///    FROM Users
        ///    WHERE Email = @Email
        ///)
        ///THEN 1
        ///ELSE 0
        ///END AS BIT).
        /// </summary>
        public static string Users_EmailExists {
            get {
                return ResourceManager.GetString("Users_EmailExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Users
        ///(
        ///    Id,
        ///    Email,
        ///    FirstName,
        ///    LastName,
        ///    LoyaltyPoints,
        ///    AvatarURL,
        ///    PasswordHash,
        ///    MFAType,
        ///    TFASecret,
        ///    IsVerified,
        ///    Status,
        ///    RoleId,
        ///    LastLoginAt,
        ///    CreatedAt,
        ///    UpdatedAt
        ///)
        ///VALUES
        ///(
        ///    @Id,
        ///    @Email,
        ///    @FirstName,
        ///    @LastName,
        ///    @LoyaltyPoints,
        ///    @AvatarURL,
        ///    @PasswordHash,
        ///    @MFAType,
        ///    @TFASecret,
        ///    @IsVerified,
        ///    @Status,
        ///    @RoleId,
        ///    @LastLoginAt,
        ///    @CreatedAt,
        ///    @UpdatedAt
        ///).
        /// </summary>
        public static string Users_Insert {
            get {
                return ResourceManager.GetString("Users_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    Id,
        ///    Email,
        ///    FirstName,
        ///    LastName,
        ///    LoyaltyPoints,
        ///    AvatarURL,
        ///    PasswordHash,
        ///    MFAType,
        ///    TFASecret,
        ///    IsVerified,
        ///    Status,
        ///    RoleId,
        ///    LastLoginAt,
        ///    CreatedAt,
        ///    UpdatedAt
        ///FROM Users.
        /// </summary>
        public static string Users_SelectAll {
            get {
                return ResourceManager.GetString("Users_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///    u.Id,
        ///    u.Email,
        ///    u.PasswordHash,
        ///    u.FirstName,
        ///    u.LastName,
        ///    u.IsVerified,
        ///    u.Status,
        ///    u.RoleId,
        ///    r.Name AS RoleName
        ///FROM Users u
        ///INNER JOIN Roles r ON r.Id = u.RoleId
        ///WHERE u.Email = @Email.
        /// </summary>
        public static string Users_SelectByEmail {
            get {
                return ResourceManager.GetString("Users_SelectByEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    Id,
        ///    Email,
        ///    FirstName,
        ///    LastName,
        ///    LoyaltyPoints,
        ///    AvatarURL,
        ///    PasswordHash,
        ///    MFAType,
        ///    TFASecret,
        ///    IsVerified,
        ///    Status,
        ///    RoleId,
        ///    LastLoginAt,
        ///    CreatedAt,
        ///    UpdatedAt
        ///FROM Users
        ///WHERE Id = @Id.
        /// </summary>
        public static string Users_SelectById {
            get {
                return ResourceManager.GetString("Users_SelectById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  SELECT
        ///        Id,
        ///        Email,
        ///        FirstName,
        ///        LastName,
        ///        LoyaltyPoints,
        ///        AvatarURL,
        ///        PasswordHash,
        ///        MFAType,
        ///        TFASecret,
        ///        IsVerified,
        ///        Status,
        ///        RoleId,
        ///        LastLoginAt,
        ///        CreatedAt,
        ///        UpdatedAt
        ///    FROM Users
        ///    WHERE RoleId = @RoleId.
        /// </summary>
        public static string Users_SelectByRoleId {
            get {
                return ResourceManager.GetString("Users_SelectByRoleId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///        Id,
        ///        Email,
        ///        FirstName,
        ///        LastName,
        ///        LoyaltyPoints,
        ///        AvatarURL,
        ///        PasswordHash,
        ///        MFAType,
        ///        TFASecret,
        ///        IsVerified,
        ///        Status,
        ///        RoleId,
        ///        LastLoginAt,
        ///        CreatedAt,
        ///        UpdatedAt
        ///    FROM Users
        ///    WHERE Status = @Status.
        /// </summary>
        public static string Users_SelectByStatus {
            get {
                return ResourceManager.GetString("Users_SelectByStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  SELECT
        ///        Id,
        ///        Email,
        ///        FirstName,
        ///        LastName,
        ///        LoyaltyPoints,
        ///        AvatarURL,
        ///        PasswordHash,
        ///        MFAType,
        ///        TFASecret,
        ///        IsVerified,
        ///        Status,
        ///        RoleId,
        ///        LastLoginAt,
        ///        CreatedAt,
        ///        UpdatedAt
        ///    FROM Users
        ///    WHERE Email = @Email.
        /// </summary>
        public static string Users_SelectUserByEmail {
            get {
                return ResourceManager.GetString("Users_SelectUserByEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Users
        ///SET
        ///    Email = @Email,
        ///    FirstName = @FirstName,
        ///    LastName = @LastName,
        ///    LoyaltyPoints = @LoyaltyPoints,
        ///    AvatarURL = @AvatarURL,
        ///    PasswordHash = @PasswordHash,
        ///    MFAType = @MFAType,
        ///    TFASecret = @TFASecret,
        ///    IsVerified = @IsVerified,
        ///    Status = @Status,
        ///    RoleId = @RoleId,
        ///    LastLoginAt = @LastLoginAt,
        ///    UpdatedAt = @UpdatedAt
        ///WHERE Id = @Id.
        /// </summary>
        public static string Users_Update {
            get {
                return ResourceManager.GetString("Users_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Users
        ///SET
        ///    LastLoginAt = @LastLoginAt,
        ///    UpdatedAt = @UpdatedAt
        ///WHERE Id = @UserId.
        /// </summary>
        public static string Users_UpdateLastLogin {
            get {
                return ResourceManager.GetString("Users_UpdateLastLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   UPDATE Users
        ///    SET
        ///        Status = @Status,
        ///        UpdatedAt = @UpdatedAt
        ///    WHERE Id = @UserId.
        /// </summary>
        public static string Users_UpdateStatus {
            get {
                return ResourceManager.GetString("Users_UpdateStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     UPDATE Users
        ///    SET
        ///        IsVerified = @IsVerified,
        ///        UpdatedAt = @UpdatedAt
        ///    WHERE Id = @UserId.
        /// </summary>
        public static string Users_UpdateVerification {
            get {
                return ResourceManager.GetString("Users_UpdateVerification", resourceCulture);
            }
        }
    }
}
