//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SQLQueries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SQLQueries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DAL.SQLQueries", typeof(SQLQueries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT CASE
        ///WHEN EXISTS (SELECT 1 FROM Users WHERE Email = @Email)
        ///THEN CAST(1 AS BIT)
        ///ELSE CAST(0 AS BIT)
        ///END.
        /// </summary>
        internal static string EmailExists {
            get {
                return ResourceManager.GetString("EmailExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Users
        ///(
        ///    Id,
        ///    Email,
        ///    FirstName,
        ///    LastName,
        ///    PasswordHash,
        ///    RoleId,
        ///    Status,
        ///    IsVerified,
        ///    CreatedAt
        ///)
        ///VALUES
        ///(
        ///    @Id,
        ///    @Email,
        ///    @FirstName,
        ///    @LastName,
        ///    @PasswordHash,
        ///    @RoleId,
        ///    @Status,
        ///    @IsVerified,
        ///    @CreatedAt
        ///).
        /// </summary>
        internal static string InsertUser {
            get {
                return ResourceManager.GetString("InsertUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///    u.Id,
        ///    u.Email,
        ///    u.PasswordHash,
        ///    u.FirstName,
        ///    u.LastName,
        ///    r.Name AS RoleName
        ///FROM Users u
        ///JOIN Roles r ON r.Id = u.RoleId
        ///WHERE u.Email = @Email.
        /// </summary>
        internal static string SelectUserByEmail {
            get {
                return ResourceManager.GetString("SelectUserByEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    Id,
        ///    Email,
        ///    FirstName,
        ///    LastName,
        ///    LoyaltyPoints,
        ///    AvatarURL,
        ///    PasswordHash,
        ///    MFAType,
        ///    TFASecret,
        ///    IsVerified,
        ///    Status,
        ///    RoleId,
        ///    LastLoginAt,
        ///    CreatedAt,
        ///    UpdatedAt
        ///FROM Users
        ///WHERE Id = @UserId.
        /// </summary>
        internal static string SelectUserById {
            get {
                return ResourceManager.GetString("SelectUserById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Users
        ///SET LastLoginAt = @LastLoginAt
        ///WHERE Id = @UserId.
        /// </summary>
        internal static string UpdateLastLogin {
            get {
                return ResourceManager.GetString("UpdateLastLogin", resourceCulture);
            }
        }
    }
}
